FROM python:3.9-slim

# ติดตั้ง Tesseract OCR
RUN apt-get update && apt-get install -y tesseract-ocr

# คัดลอกโค้ดไปยังเซิร์ฟเวอร์
WORKDIR /app
COPY . /app

# ติดตั้ง dependencies จาก requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

# กำหนด path สำหรับ Tesseract
ENV TESSDATA_PREFIX=/usr/share/tesseract-ocr/4.00/tessdata

# รัน Flask app
CMD ["gunicorn", "-w", "4", "-b", "0.0.0.0:5000", "app:app"]
